### ISSUE TITLE
结果复现存在问题

### ISSUE THREAD

**Issue by LemonQC** [hustvl/Query6DoF#2]
尝试train Real数据集，得到下面的结果
![image](https://github.com/hustvl/Query6DoF/assets/30914380/3ce5bf22-8f67-4752-a806-473c66ba29b6)

buzhid不知道您能否提供一下训练参数呢

**Comment by RuiqiWang00** [comment]
训练参数在config/run.py,

**Comment by LemonQC** [comment]
我们是直接默认运行的：
python tools/train.py --cfg config/run.py --gpus 0,1
![image](https://github.com/hustvl/Query6DoF/assets/30914380/6feaff44-3d69-4d51-94a4-05278a7edb03)

**Comment by RuiqiWang00** [comment]
在测试时，是否将config/run_eval_real.py中的RESUME_FILE修改为最后训练得到的模型名字？请问您是否使用CAMERA数据集一起训练？

**Comment by LemonQC** [comment]
没有一起训练，模型名字修改了

**Comment by RuiqiWang00** [comment]
只在real数据集上训练的参数略有不同，之后会提供。

**Comment by LemonQC** [comment]
混合起来训练会得到和论文中一样的结果么

**Comment by RuiqiWang00** [comment]
论文的设置是混合训练

**Comment by LemonQC** [comment]
好的，感谢您的回复，我再尝试一下混合训练，看看结果

**Comment by RuiqiWang00** [comment]
如果只是用real，你可以将config修改为
![image](https://github.com/hustvl/Query6DoF/assets/47249329/44f5ec83-b795-4337-ac18-0907981b258e)
例如，我这里得到的一个结果为
![image](https://github.com/hustvl/Query6DoF/assets/47249329/79093704-237f-4b24-9b52-5b8adf9fd34f)
最终的结果可能会有1-2的波动，如果使用CAMERA数据集混合训练精度更高。
我的训练由四块显卡完成，所以总batchsize为45，如果batchsize发生变化，请将SCHEDULER下的参数T_max修改为相应的step数量，以确保学习率衰减充分。

**Comment by LemonQC** [comment]
![image](https://github.com/hustvl/Query6DoF/assets/30914380/fc2ad377-0848-440b-940f-0a6784866b0f)
，这个是论文j结果吧，好像Iou75等几个差的点有点多吧

**Comment by RuiqiWang00** [comment]
论文的设定是real和camera混合训练

**Comment by LemonQC** [comment]
哦哦，就是单纯训练的话，我也能训练起来，但是，差距还是蛮大的

**Comment by LemonQC** [comment]
您论文提到是在一个RTX 2080TI操作的，您训练也是基于这个么，是一个卡训练的，只是batch设置的很大

**Comment by RuiqiWang00** [comment]
训练RTX 3090*4， 单卡batchsize 15

**Comment by LemonQC** [comment]
但是用3090，我这边出现线程卡死导致显存无法释放的问题，不知道是否程序哪里有改动

**Comment by RuiqiWang00** [comment]
我这边并没有这种情况

**Comment by LemonQC** [comment]
好的，谢谢您的帮助
