### ISSUE TITLE
关于Camera上的结果

### ISSUE THREAD

**Issue by LemonQC** [hustvl/Query6DoF#5]
是直接在CMAERA上训练得到结果还是CAMERA+REAL训练后得到的结果呢。要是单独训练，能否提供一下参考配置文件

**Comment by RuiqiWang00** [comment]
CAMERA+REAL训练后得到的结果

**Comment by LemonQC** [comment]
好的，感谢您的帮助，已经复现了，基本幅度为1-2个点
