### ISSUE TITLE
数据预处理时的疑问

### ISSUE THREAD

**Issue by sdu-huanhq** [hustvl/Query6DoF#8]
作者您好：
请问在`dataset/pose_dataset.py`文件中的的[第225行](https://github.com/hustvl/Query6DoF/blob/b4576b05a60c457079c964e99843fc1b8b26bab1/dataset/pose_dataset.py#L225)：
```
        sRT[:3, :3] = scale * rotation
```
为什么要将rotation乘以scale呢？这样旋转矩阵将不再是一个标准的旋转矩阵，因为可能不再正交，请问为什么要这么做？

**Comment by RuiqiWang00** [comment]
The coordinate transformation can be expressed by the following formula.
![image](https://github.com/hustvl/Query6DoF/assets/47249329/73058c95-8662-404c-9f4d-cecf11e571a5)
 The transformation can be represented by combining s, R, and t into a single matrix. In homogeneous coordinates, the transformation can then be achieved by multiplying with this matrix. Here, this representation is employed for the convenience of visualization.

**Comment by sdu-huanhq** [comment]
非常感谢
