### ISSUE TITLE
关于训练时数据迭代的问题

### ISSUE THREAD

**Issue by sdu-huanhq** [hustvl/Query6DoF#9]
作者您好：
请问您在训练时有没有遇到过从Dataloader取数据时时快时慢的问题，比如取第一到第10个batch用了20秒，但到第21个batch就要卡15秒，这种情况您遇到过吗？

**Comment by RuiqiWang00** [comment]
这极大可能是因为图片读取速度过慢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月15日(周一) 晚上10:06
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [hustvl/Query6DoF] 关于训练时数据迭代的问题 (Issue #9)




 
作者您好：
 请问您在训练时有没有遇到过从Dataloader取数据时时快时慢的问题，比如取第一到第10个batch用了20秒，但到第21个batch就要卡15秒，这种情况您遇到过吗？

**Comment by sdu-huanhq** [comment]
> 这极大可能是因为图片读取速度过慢
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年1月15日(周一) 晚上10:06 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [hustvl/Query6DoF] 关于训练时数据迭代的问题 (Issue #9) 作者您好： 请问您在训练时有没有遇到过从Dataloader取数据时时快时慢的问题，比如取第一到第10个batch用了20秒，但到第21个batch就要卡15秒，这种情况您遇到过吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

![image](https://github.com/hustvl/Query6DoF/assets/57307657/4983472a-d120-45ad-8001-d72a06079be7)
这是训练的日志，有的时候样本处理速度就一点几零点几

**Comment by sdu-huanhq** [comment]
> 这极大可能是因为图片读取速度过慢
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年1月15日(周一) 晚上10:06 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [hustvl/Query6DoF] 关于训练时数据迭代的问题 (Issue #9) 作者您好： 请问您在训练时有没有遇到过从Dataloader取数据时时快时慢的问题，比如取第一到第10个batch用了20秒，但到第21个batch就要卡15秒，这种情况您遇到过吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

![a021cc6661f96ab43863959ab7e20ba](https://github.com/hustvl/Query6DoF/assets/57307657/dc23b409-4151-48b9-918e-1e51bd47e764)
这是训练日志，有时候处理速度一点几或者零点几

**Comment by sdu-huanhq** [comment]
作者请问您在训练的时候有没有遇到这种问题

**Comment by RuiqiWang00** [comment]
这种情况通常是因为从硬盘读取图片速度过慢，建议使用固态硬盘
